version: '3'

services:
  # DB
  postgres:
    restart: always
    volumes:
    - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    build: ./postgres
    ## disable logging
    # logging:
    #     driver: none
  tally-graphql:
    image: hasura/graphql-engine:v1.3.0
    depends_on:
    - postgres
    restart: always
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:15672']
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true' # set to 'false' to disable console
      HASURA_GRAPHQL_DEV_MODE: 'true' # dev mode
      HASURA_GRAPHQL_SERVER_PORT: 8888
      HASURA_GRAPHQL_MIGRATIONS_DIR: '/hasura-migrations'
      HASURA_GRAPHQL_METADATA_DIR: '/hasura-metadata'
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
    volumes:
      - ./hasura/migrations:/hasura-migrations
      - ./hasura/metadata:/hasura-metadata
    command:
    - graphql-engine
    - serve
    ports:
      - 8888:8888
      - 15672:15672
    ## disable logging
    # logging:
    #   driver: none

  # Front website
  tally-web:
    environment:
      - NODE_ENV=development
      - PORT=9999
      - NEXT_PUBLIC_RELAY_ENDPOINT=http://tally-graphql:8888/v1/graphql
      - CHOKIDAR_USEPOLLING=true
    depends_on:
    - tally-graphql
    # Volumes only for dev, since itll be compiled for prod
    volumes:
      - ./tally-web/:/webroot/default
    build: ./tally-web
    command: yarn dev

  # Proxy server
  caddy:
    image: caddy/caddy
    depends_on:
    - postgres
    - tally-graphql
    - tally-web
    restart: always
    ports:
    - 8080:8080
    - 9090:9090
    - 443:443
    - 80:80
    volumes:
    - ./Caddyfile:/etc/caddy/Caddyfile
    - ./certs:/root/.caddy
volumes:
  pg_data: